// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://semmqysqmbzumjjuohhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbW1xeXNxbWJ6dW1qanVvaGh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2OTA4NDUsImV4cCI6MjA1NTI2Njg0NX0.lh1tp9TJxEBRgQI5fUBMPJRBiJldPUTOjv61p1Mhb8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);